name: sglofts
favicon: null
layout_spectrum: 0.5274
typography_spectrum: 0.5251711923629045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#06050a'
    - '#c9d0fa'
    - '#6b6879'
    - '#de8d4c'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
