name: sglofts
favicon: null
layout_spectrum: 0.00417
typography_spectrum: 0.5251711923629045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9d2cc'
    - '#fdfdfd'
    - '#ab8f7a'
    - '#323031'
    - '#91705d'
  brandStrength: 0.375
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
