name: sglofts
favicon: null
layout_spectrum: 0.09599
typography_spectrum: 0.5251711923629045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2b292e'
    - '#daccc2'
    - '#ca753c'
    - '#6b8292'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
