name: sglofts
favicon: null
layout_spectrum: 0.00417
typography_spectrum: 0.15623
title: CĂN HỘ TẠI SÀI GÒN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#636361'
    - '#b8b9b4'
    - '#1a1a18'
    - '#dbdbdb'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
