name: sglofts
favicon: null
layout_spectrum: 0.09599
typography_spectrum: 0.5251711923629045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5e5654'
    - '#060000'
    - '#91bae9'
    - '#b6583b'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
